services:
    postgres:
        image: postgres:14
        environment:
            - POSTGRES_DB=${POSTGRES_DB_AF}
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD_AF
            - POSTGRES_USER=airflow
        volumes:
            - ./database/:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready -d db -U airflow"]
            interval: 5s
            retries: 5
        ports:
          - "5433:5432"
        restart: always

    scheduler:
        build: .
        command: poetry run airflow scheduler
        restart: on-failure
        depends_on:
            - postgres
        environment:
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:$POSTGRES_PASSWORD_AF@postgres:5432/db
            - AIRFLOW__CORE__LOAD_EXAMPLES=false
            - PYTHONPATH=/app/airflow/src
        volumes:
            - ./dags:/app/airflow/dags
            - ./src:/app/airflow/src
            - ./data:/app/airflow/data
            - ./logs:/app/airflow/logs
            - /home/peripriego/.gcp_keys:/app/airflow/.gcp_keys
            - ./dbt_cgpdata:/app/airflow/dbt_cgpdata


    webserver:
        build: .
        command: poetry run scripts/entrypoint.sh
        restart: on-failure
        depends_on:
            - postgres
            - scheduler
        environment:
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:$POSTGRES_PASSWORD_AF@postgres:5432/db
            - POSTGRES_DB=${POSTGRES_DB_AF}
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD_AF
            - POSTGRES_USER=airflow
            - PYTHONPATH=/app/airflow/src
        volumes:
            - ./dags:/app/airflow/dags
            - ./src:/app/airflow/src
            - ./data:/app/airflow/data
            - ./logs:/app/airflow/logs
            - /home/peripriego/.gcp_keys:/app/airflow/.gcp_keys
            - ./dbt_cgpdata:/app/airflow/dbt_cgpdata
        ports:
            - "8080:8080"
        healthcheck:
            test: ["CMD-SHELL", "[ -f /home/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    cgp-grafana:
      image: grafana/grafana
      container_name: cgp-grafana
      restart: unless-stopped
      ports:
      - 3000:3000
      environment:
        POSTGRES_DATABASE_URL: postgresql+psycopg2://${APP_DB_USER}:${APP_DB_PASS}@cgp-database:5442/${APP_DB_NAME}
        GF_SECURITY_ADMIN_USER: "admin"
      env_file:
      - ./.env
      user: '0'
      volumes:
        - ./grafana_data:/var/lib/grafana
      depends_on:
        - cgp-database


    cgp-database:
      image: postgres:14.2
      container_name: cgp-database
      restart: on-failure
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
      volumes:
        - ./scripts/db_init/:/docker-entrypoint-initdb.d/
        - ./database_cgp/:/var/lib/postgresql/data
      ports:
        - 5442:5432
      environment:
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD_CGP
        - POSTGRES_USER=$POSTGRES_USER_CGP
        - POSTGRES_DB=$POSTGRES_DB_CGP
        - APP_DB_USER=$APP_DB_USER
        - APP_DB_PASS=$APP_DB_PASS
        - APP_DB_NAME=$APP_DB_NAME
