dbt_cgpdata:
  outputs:
    dev:
      dataset: cgpdata_lwb
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/hugh.harford/.gcp_keys/lwb2_cgp_data.json
      location: EU
      method: service-account
      priority: interactive
      project: condorgp-451516
      threads: 1
      type: bigquery
    docker_compose:
      dataset: cgpdata_lwb
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ../.gcp_keys/lwb2_cgp_data.json
      location: EU
      method: service-account
      priority: interactive
      project: condorgp-451516
      threads: 1
      type: bigquery
  target: docker_compose
