"""layer_name into datafiles table

Revision ID: baa457147ac2
Revises: d1588a99d9ae
Create Date: 2025-03-14 22:13:23.944013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baa457147ac2'
down_revision: Union[str, None] = 'd1588a99d9ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datafiles', sa.Column('layer_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datafiles', 'layer_name')
    # ### end Alembic commands ###
