"""blob_size into datafiles table

Revision ID: d1588a99d9ae
Revises: 223914636249
Create Date: 2025-03-14 21:43:50.374861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1588a99d9ae'
down_revision: Union[str, None] = '223914636249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datafiles', sa.Column('blob_size', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datafiles', 'blob_size')
    # ### end Alembic commands ###
