"""added datafiles table

Revision ID: e8650890600b
Revises: 
Create Date: 2025-03-13 12:04:41.724508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8650890600b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datafiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_file_name', sa.String(), nullable=False),
    sa.Column('upload_time_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datafiles')
    # ### end Alembic commands ###
